Product.development
ManojParmar-MTAJ/StockManagement pull request #6
Opened 2018-01-29 12:23 UTC by dharmarajsinh143

2018-01-29 12:26 UTC, ManojParmar-MTAJ commented on app/controllers/products_controller.rb
> +
fix indentation and remove extra spaces

2018-01-29 12:27 UTC, RaviMariya-MTAJ commented on app/controllers/products_controller.rb
> +
remove blank lines

2018-01-29 12:28 UTC, RaviMariya-MTAJ commented on app/controllers/products_controller.rb
> +
same here

2018-01-29 12:28 UTC, RaviMariya-MTAJ commented on app/controllers/products_controller.rb
> +
remove blank line from everywhere

2018-01-29 12:29 UTC, RaviMariya-MTAJ commented on app/views/products/_form.html.erb
> +<tr>
fix indentation

2018-01-29 12:29 UTC, RaviMariya-MTAJ commented on app/views/products/show.html.erb
> +</table>
keep 2spaces indentation in each file

2018-01-29 12:30 UTC, RaviMariya-MTAJ requested changes
please review the comments and fix as suggested

2018-01-30 09:45 UTC, RaviMariya-MTAJ commented on app/views/products/_form.html.erb
> +      <td> <%= form.text_field :product_name, id: :product_name %></td>
where are you using this id?

2018-01-30 09:46 UTC, RaviMariya-MTAJ commented on app/views/products/_form.html.erb
> +      <td> <%= form.text_field :product_code, id: :product_code %></td>
why you're giving id in each field?

2018-01-30 09:46 UTC, RaviMariya-MTAJ commented on app/views/products/_form.html.erb
> +   <td><%= form.number_field :product_price, id: :product_price%></td>
same everywhere

2018-01-30 09:46 UTC, RaviMariya-MTAJ commented on app/views/products/edit.html.erb
> +<%= render 'form', product: @product %>
do we need to pass `@product` here?

2018-01-30 09:46 UTC, RaviMariya-MTAJ commented on app/views/products/new.html.erb
> +<%= render 'form', product: @product %>
same here

2018-01-31 05:53 UTC, merged